version: '3'
services:
  dev:
    build: .
    volumes:
      - .:/codes/
      - /codes/node_modules
  docs:
    build:
      context: .
      dockerfile: Dockerfile.golang
    command: terraform-docs markdown table ./module
    volumes:
      - .:/codes/
